# Generated by Django 4.1.10 on 2023-11-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HR_description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                ("empID", models.IntegerField(max_length=5)),
                ("Salary", models.IntegerField(max_length=10)),
                ("position", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=10)),
                ("sex", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="HR_department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "HR_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.hr_description",
                    ),
                ),
                (
                    "departmant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.department",
                    ),
                ),
            ],
        ),
    ]
