# Generated by Django 4.1.10 on 2023-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_hr_description_added_by_hr_description_added_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proj_name", models.CharField(max_length=255)),
                ("date", models.DateField(null=True)),
                ("type_v", models.CharField(max_length=255)),
            ],
        ),
    ]
