# Generated by Django 4.1.10 on 2023-11-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0003_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="added_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
