# Generated by Django 4.1.10 on 2023-11-05 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_setting_added_by_setting_added_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setting",
            old_name="date",
            new_name="Date",
        ),
    ]
