# Generated by Django 4.1.10 on 2023-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0006_settingtool_delete_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="userall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("account", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
