# Generated by Django 4.2.7 on 2023-11-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_userall"),
    ]

    operations = [
        migrations.CreateModel(
            name="sleephealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personID", models.IntegerField()),
                ("age", models.CharField(max_length=255)),
                ("occupation", models.CharField(max_length=255)),
                ("sleep_duration", models.IntegerField()),
                ("quality_sleep", models.IntegerField()),
                ("bmi_category", models.CharField(max_length=255)),
                ("heart_rate", models.IntegerField()),
                ("daily_step", models.IntegerField()),
                ("sleep_disorder", models.CharField(max_length=255)),
            ],
        ),
    ]
